#pragma once

namespace sk
{
	// Contiguous platform independent input codes
	enum class Keyboard : short
	{
		Unknown          = 0,

		Space            = 1,
		Apostrophe       = 2, 
		Comma            = 3, 
		Minus            = 4, 
		Period           = 5, 
		Slash            = 6, 
		Num0             = 7,
		Num1             = 8,
		Num2             = 9,
		Num3             = 10,
		Num4             = 11,
		Num5             = 12,
		Num6             = 13,
		Num7             = 14,
		Num8             = 15,
		Num9             = 16,
		Semicolon        = 17, 
		Equal            = 18, 
		A                = 19,
		B                = 20,
		C                = 21,
		D                = 22,
		E                = 23,
		F                = 24,
		G                = 25,
		H                = 26,
		I                = 27,
		J                = 28,
		K                = 29,
		L                = 30,
		M                = 31,
		N                = 32,
		O                = 33,
		P                = 34,
		Q                = 35,
		R                = 36,
		S                = 37,
		T                = 38,
		U                = 39,
		V                = 40,
		W                = 41,
		X                = 42,
		Y                = 43,
		Z                = 44,
		LeftBracket      = 45, 
		Backslash        = 46, 
		RightBracket     = 47, 
		Grave            = 48, 
			
		Escape           = 49,
		Enter            = 50,
		Tab              = 51,
		Backspace        = 52,
		Insert           = 53,
		Delete           = 54,
		Right            = 55,
		Left             = 56,
		Down             = 57,
		Up               = 58,
		PageUp           = 59,
		PageDown         = 60,
		Home             = 61,
		End              = 62,
		CapsLock         = 63,
		ScrollLock       = 64,
		NumLock          = 65,
		PrintScreen      = 66,
		Pause            = 67,
		F1               = 68,
		F2               = 69,
		F3               = 70,
		F4               = 71,
		F5               = 72,
		F6               = 73,
		F7               = 74,
		F8               = 75,
		F9               = 76,
		F10              = 77,
		F11              = 78,
		F12              = 79,
		F13              = 80,
		F14              = 81,
		F15              = 82,
		F16              = 83,
		F17              = 84,
		F18              = 85,
		F19              = 86,
		F20              = 87,
		F21              = 88,
		F22              = 89,
		F23              = 90,
		F24              = 91,
		F25              = 92,
		KP_0             = 93,
		KP_1             = 94,
		KP_2             = 95,
		KP_3             = 96,
		KP_4             = 97,
		KP_5             = 98,
		KP_6             = 99,
		KP_7             = 100,
		KP_8             = 101,
		KP_9             = 102,
		KP_Decimal       = 103,
		KP_Divide        = 104,
		KP_Multiply      = 105,
		KP_Subtract      = 106,
		KP_Add           = 107,
		KP_Enter         = 108,
		KP_Equal         = 109,
		LeftShift        = 110,
		LeftControl      = 111,
		LeftAlt          = 112,
		LeftSuper        = 113,
		RightShift       = 114,
		RightControl     = 115,
		RightAlt         = 116,
		RightSuper       = 117,
		Menu             = 118,

		Count            = Menu
	};

	enum class Mouse : short
	{
		Unknown = -1,

		Button1 = 0,
		Button2 = 1,
		Button3 = 2,
		Button4 = 3,
		Button5 = 4,
		Button6 = 5,
		Button7 = 6,
		Button8 = 7,
		ButtonLeft = Button1,
		ButtonRight = Button2,
		ButtonMiddle = Button3,

		Count = Button8
	};
}
